#!/bin/bash


arg1=$1
arg2=$2

if [ -z "$arg1" ];then
arg1='8077'
fi

if [ -z "$arg2" ];then
arg2='wsgi'
fi





# cd /kf/sdj
gunicorn --workers=4 -b 0.0.0.0:$arg1 sdj.$arg2 --threads 40 --max-requests 4096 --max-requests-jitter 512




