# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-05-23 09:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd', models.TextField(verbose_name='\u547d\u4ee4\u5185\u5bb9')),
                ('ctype', models.SmallIntegerField(blank=True, choices=[(1, 'GREP\u65e5\u5fd7'), (2, '\u5e38\u7528\u811a\u672c'), (4, 'APP\u914d\u7f6e\u8f83\u9a8c'), (6, '\u81ea\u5b9a\u4e49\u547d\u4ee4')], default=1, null=True, verbose_name='\u547d\u4ee4\u7c7b\u578b')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('end', models.BooleanField(default=False, verbose_name='\u4efb\u52a1\u5b8c\u6210')),
            ],
            options={
                'verbose_name': 'CMD\u8bb0\u5f55',
            },
        ),
        migrations.CreateModel(
            name='CMD_Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u8fd4\u56de\u4fe1\u606f')),
                ('cmd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.CMD', verbose_name='\u547d\u4ee4')),
            ],
            options={
                'verbose_name': 'CMD\u7ed3\u679c',
            },
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u7528\u4e8e\u4eba\u5de5\u8fa8\u522b\uff0c\u81ea\u52a8\u811a\u672c\u9ed8\u8ba4\u8bbe\u7f6e\u4e3a\u4e3b\u673a\u540d\uff0c\u53ef\u6539\u4e3a\u5176\u5b83\u4fbf\u4e8e\u4eba\u5458\u8bc6\u522b\u7684\u540d\u79f0', max_length=100, verbose_name='\u6807\u8bc6\u540d\u79f0')),
                ('hostname', models.CharField(help_text='\u5173\u952e\u5b57\u6bb5\uff0c\u8bf7\u8c28\u614e\u4fee\u6539', max_length=50, unique=True, verbose_name='\u4e3b\u673a\u540d/\u8ba1\u7b97\u673a\u540d')),
                ('ip', models.GenericIPAddressField(help_text='\u82e5\u6709\u591a\u4e2aIP\u4e14\u4e3b\u673a\u540d\u65e0\u6307\u5b9a\u89e3\u6790\u5219\u9ed8\u8ba4\u4e3a0.0.0.0\uff0c\u8bf7\u5728\u5ba2\u6237\u7aef/etc/hosts\u4e2d\u8bbe\u7f6e\u5176\u4e3b\u673a\u540d\u5bf9\u5e94IP\u89e3\u6790', verbose_name='\u7ba1\u7406IP')),
                ('port', models.IntegerField(blank=True, default=22, null=True, verbose_name='ssh\u7aef\u53e3')),
                ('other_ip', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u5176\u5b83IP')),
                ('status', models.SmallIntegerField(blank=True, choices=[(1, '\u5728\u7528'), (2, '\u5907\u7528'), (3, '\u6545\u969c'), (4, '\u4e0b\u7ebf'), (6, '\u5176\u5b83')], default=1, null=True, verbose_name='\u8bbe\u5907\u72b6\u6001')),
                ('asset_type', models.SmallIntegerField(blank=True, choices=[(1, '\u7269\u7406\u673a'), (2, '\u865a\u62df\u673a'), (3, '\u5bb9\u5668'), (4, 'H3C\u4ea4\u6362\u673a'), (6, '\u5176\u5b83')], default=1, null=True, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
                ('os', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='\u64cd\u4f5c\u7cfb\u7edf')),
                ('cpu_model', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='CPU\u578b\u53f7')),
                ('cpu_num', models.CharField(blank=True, default='', help_text='\u7269\u7406\u6838\u4e2a\u6570, \u903b\u8f91\u6838\u4e2a\u6570\uff0c(intel\u9ad8\u7aefCPU\u5e26\u8d85\u7ebf\u7a0b\u6280\u672f)', max_length=100, null=True, verbose_name='CPU\u6570\u91cf')),
                ('memory', models.CharField(blank=True, default='', max_length=30, null=True, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('disk', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='\u786c\u76d8\u4fe1\u606f')),
                ('vendor', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u4f9b\u5e94\u5546')),
                ('sn', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u4e3b\u673a\u5e8f\u5217\u53f7')),
                ('ports', models.TextField(blank=True, default='', help_text='\u4e3b\u673a\u4e0a\u5904\u4e8e\u76d1\u542c\u72b6\u6001\u7684TCP\u548cUDP\u7aef\u53e3', null=True, verbose_name='\u76d1\u542c\u7aef\u53e3')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('agenttime', models.DateTimeField(blank=True, help_text='\u6700\u8fd1\u4e00\u6b21\u4e3b\u673a\u5ba2\u6237\u7aef\u81ea\u52a8\u811a\u672c\u8fd0\u884c\u66f4\u65b0\u8f6f\u786c\u4ef6\u4fe1\u606f\u7684\u65f6\u95f4', null=True, verbose_name='\u914d\u7f6e\u66f4\u65b0')),
                ('buydate', models.DateField(blank=True, default=datetime.datetime.today, null=True, verbose_name='\u8d2d\u4e70\u65e5\u671f')),
                ('position', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='\u6240\u5904\u4f4d\u7f6e')),
                ('sernumb', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u670d\u52a1\u7f16\u53f7')),
                ('sercode', models.CharField(blank=True, default='', max_length=150, null=True, verbose_name='\u670d\u52a1\u4ee3\u7801')),
                ('tomcat', models.CharField(default='/data/app/tomcat', max_length=100, verbose_name='Tomcat\u76ee\u5f55')),
                ('tomcat_ver', models.CharField(blank=True, default='', max_length=50, verbose_name='Tomcat\u7248\u672c')),
                ('jdk_ver', models.CharField(blank=True, default='', max_length=50, verbose_name='JDK\u7248\u672c')),
                ('kernel', models.CharField(blank=True, default='', max_length=60, verbose_name='\u7cfb\u7edf\u5185\u6838\u7248\u672c')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
                ('admin', models.ForeignKey(blank=True, help_text='\u8d1f\u8d23\u4eba\u76f4\u63a5\u6709(\u5f53\u524d\u4e3b\u673a/\u540d\u4e0b\u4e3b\u673a)\u64cd\u4f5c\u6743\u9650', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_set2', to=settings.AUTH_USER_MODEL, verbose_name='\u7ba1\u7406\u4eba')),
            ],
            options={
                'ordering': ['group', 'ip'],
                'verbose_name': '\u4e3b\u673a',
                'permissions': (('deploy_host', 'Can deploy host'), ('webssh_host', 'Can webssh host'), ('grep_host', 'Can grep host'), ('run_sh_host', 'Can run_sh host'), ('run_cmd_host', 'Can run_cmd host'), ('other_do_host', 'Can other_do host')),
            },
        ),
        migrations.CreateModel(
            name='HostGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='\u7ec4\u540d/\u533a\u57df')),
                ('ip', models.CharField(blank=True, default='', help_text='IP\u5f00\u5934\u5b57\u7b26\uff0c\u6bd4\u5982Core\u7ec4IP\u4e3a10.2.4.\u5f00\u5934\u3002\u7528\u4e8e\u5ba2\u6237\u7aef\u811a\u672c\u6dfb\u52a0\u65b0\u4e3b\u673a\u65f6\u81ea\u52a8\u8bbe\u7f6e\u7ec4\uff0c\u4e0d\u652f\u6301\u901a\u914d\u7b26', max_length=20, verbose_name='IP\u5339\u914d')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='\u63cf\u8ff0')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u4e3b\u673a\u5206\u7ec4',
            },
        ),
        migrations.CreateModel(
            name='SH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='\u6807\u8bc6\u540d')),
                ('fname', models.CharField(default='', help_text='\u4f7f\u811a\u672c\u80fd\u901a\u8fc7URL\u5f62\u5f0f\u6765\u8c03\u7528\uff0chttp://10.2.21.34:8088/api/sh/\u6587\u4ef6\u540d\uff0c\u5e76\u4e14\u901a\u8fc7\u540e\u7f00\u540d\u533a\u5206py\u3001sh\u811a\u672c', max_length=100, verbose_name='\u6587\u4ef6\u540d')),
                ('sh', models.SmallIntegerField(blank=True, choices=[(1, '\u9ed8\u8ba4'), (2, 'H3C\u4ea4\u6362\u673a'), (3, 'APP\u914d\u7f6e')], default=1, null=True, verbose_name='\u811a\u672c\u7c7b\u578b')),
                ('cmd', models.TextField(blank=True, null=True, verbose_name='\u811a\u672c\u5185\u5bb9')),
                ('text', models.TextField(blank=True, null=True, verbose_name='\u5907\u6ce8')),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
            ],
            options={
                'ordering': ['sh', 'fname'],
                'verbose_name': '\u5e38\u7528\u547d\u4ee4/\u811a\u672c',
            },
        ),
        migrations.CreateModel(
            name='SshUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', help_text='\u6807\u8bc6\u540d\u79f0\uff0c\u5f53\u4e0d\u540c\u670d\u52a1\u5668\u4f7f\u7528\u76f8\u540c\u7684SSH\u8d26\u53f7\u540d\uff0c\u4f46\u5bc6\u7801\u4e0d\u540c\u65f6\uff0c\u6b64\u9879\u540d\u79f0\u53ef\u8fdb\u884c\u533a\u5206\u3002', max_length=50, verbose_name='\u540d\u79f0')),
                ('username', models.CharField(default='', max_length=50, verbose_name='SSH\u8d26\u53f7')),
                ('password', models.CharField(blank=True, default='', help_text='\u82e5\u4e0d\u60f3\u4fee\u6539\u539f\u5bc6\u7801\uff0c\u4e0d\u7528\u8bbe\u7f6e\u6b64\u9879', max_length=50, null=True, verbose_name='\u5bc6\u7801')),
                ('changetime', models.DateTimeField(auto_now=True, null=True, verbose_name='\u6700\u540e\u4fee\u6539')),
                ('text', models.TextField(blank=True, default='', null=True, verbose_name='\u5907\u6ce8\u4fe1\u606f')),
            ],
            options={
                'ordering': ['name'],
                'verbose_name': '\u4e3b\u673aSSH\u7528\u6237',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sshuser',
            unique_together=set([('name', 'username')]),
        ),
        migrations.AlterUniqueTogether(
            name='sh',
            unique_together=set([('sh', 'fname')]),
        ),
        migrations.AddField(
            model_name='host',
            name='group',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.HostGroup', verbose_name='\u7ec4/\u5b89\u5168\u533a\u57df'),
        ),
        migrations.AddField(
            model_name='host',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='\u8bbe\u5907\u7c7b\u578b\u4e3a\u865a\u62df\u673a/\u5bb9\u5668\u65f6\uff0c\u8bbe\u7f6e\u6240\u5728\u7269\u7406\u673a', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.Host', verbose_name='\u6240\u5c5e\u7269\u7406\u673a'),
        ),
        migrations.AddField(
            model_name='host',
            name='ssh_user',
            field=models.ForeignKey(blank=True, help_text='\u5f53\u524d\u4e3b\u673a\u7684SSH\u7528\u6237\uff0c\u7528\u4e8essh\u8fde\u63a5\u6267\u884c\u547d\u4ee4\u6216\u7ec8\u7aefWEB SSH', null=True, on_delete=django.db.models.deletion.SET_NULL, to='cmdb.SshUser', verbose_name='SSH\u7ec8\u7aef\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='host',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='\u7f51\u7ad9\u54ea\u4e9b\u7528\u6237\u80fd\u5bf9\u5f53\u524d\u4e3b\u673a\u8fdb\u884c\u64cd\u4f5c\uff0c\u8d85\u7ea7\u7528\u6237\u76f4\u63a5\u6709\u64cd\u4f5c\u6743\u9650', to=settings.AUTH_USER_MODEL, verbose_name='\u7f51\u7ad9\u7528\u6237\u6743\u9650'),
        ),
        migrations.AddField(
            model_name='host',
            name='usergroup',
            field=models.ManyToManyField(blank=True, help_text='\u7f51\u7ad9\u54ea\u4e9b\u7528\u6237\u7ec4\u80fd\u5bf9\u5f53\u524d\u4e3b\u673a\u8fdb\u884c\u64cd\u4f5c', to='auth.Group', verbose_name='\u7f51\u7ad9\u7528\u6237\u7ec4'),
        ),
        migrations.AddField(
            model_name='cmd_log',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cmdb.Host', verbose_name='\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='cmd',
            name='host',
            field=models.ManyToManyField(blank=True, to='cmdb.Host', verbose_name='\u6267\u884c\u4e3b\u673a'),
        ),
        migrations.AddField(
            model_name='cmd',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u4eba'),
        ),
    ]
